
// This file has been generated by the GUI designer. Do not modify.
namespace NameGenerator
{
	public partial class MainWindow
	{
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.Entry txtbox1;
		
		private global::Gtk.HBox hbox2;
		
		private global::Gtk.VBox vbox7;
		
		private global::Gtk.HBox hbox3;
		
		private global::Gtk.Label label5;
		
		private global::Gtk.HBox hbox4;
		
		private global::Gtk.ComboBox combobox4;
		
		private global::Gtk.HBox hbox5;
		
		private global::Gtk.Label label6;
		
		private global::Gtk.ComboBox combobox5;
		
		private global::Gtk.VBox vbox9;
		
		private global::Gtk.Label label7;
		
		private global::Gtk.VBox vbox3;
		
		private global::Gtk.Button button3;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget NameGenerator.MainWindow
			this.Name = "NameGenerator.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("Name Generator");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child NameGenerator.MainWindow.Gtk.Container+ContainerChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Name:");
			this.vbox1.Add (this.label1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.label1]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			this.hbox1.Add (this.vbox1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox1]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.txtbox1 = new global::Gtk.Entry ();
			this.txtbox1.CanFocus = true;
			this.txtbox1.Name = "txtbox1";
			this.txtbox1.IsEditable = true;
			this.txtbox1.InvisibleChar = '•';
			this.vbox2.Add (this.txtbox1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.txtbox1]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.vbox7 = new global::Gtk.VBox ();
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 6;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Length:");
			this.hbox3.Add (this.label5);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.label5]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.combobox4 = global::Gtk.ComboBox.NewText ();
			this.combobox4.AppendText (global::Mono.Unix.Catalog.GetString ("3"));
			this.combobox4.AppendText (global::Mono.Unix.Catalog.GetString ("4"));
			this.combobox4.AppendText (global::Mono.Unix.Catalog.GetString ("5"));
			this.combobox4.AppendText (global::Mono.Unix.Catalog.GetString ("6"));
			this.combobox4.AppendText (global::Mono.Unix.Catalog.GetString ("7"));
			this.combobox4.AppendText (global::Mono.Unix.Catalog.GetString ("8"));
			this.combobox4.AppendText (global::Mono.Unix.Catalog.GetString ("9"));
			this.combobox4.AppendText (global::Mono.Unix.Catalog.GetString ("10"));
			this.combobox4.AppendText (global::Mono.Unix.Catalog.GetString ("11"));
			this.combobox4.AppendText (global::Mono.Unix.Catalog.GetString ("12"));
			this.combobox4.CanDefault = true;
			this.combobox4.Name = "combobox4";
			this.hbox4.Add (this.combobox4);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.combobox4]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			this.hbox3.Add (this.hbox4);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.hbox4]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("-");
			this.hbox5.Add (this.label6);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.label6]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.combobox5 = global::Gtk.ComboBox.NewText ();
			this.combobox5.AppendText (global::Mono.Unix.Catalog.GetString ("3"));
			this.combobox5.AppendText (global::Mono.Unix.Catalog.GetString ("4"));
			this.combobox5.AppendText (global::Mono.Unix.Catalog.GetString ("5"));
			this.combobox5.AppendText (global::Mono.Unix.Catalog.GetString ("6"));
			this.combobox5.AppendText (global::Mono.Unix.Catalog.GetString ("7"));
			this.combobox5.AppendText (global::Mono.Unix.Catalog.GetString ("8"));
			this.combobox5.AppendText (global::Mono.Unix.Catalog.GetString ("9"));
			this.combobox5.AppendText (global::Mono.Unix.Catalog.GetString ("10"));
			this.combobox5.AppendText (global::Mono.Unix.Catalog.GetString ("11"));
			this.combobox5.AppendText (global::Mono.Unix.Catalog.GetString ("12"));
			this.combobox5.Name = "combobox5";
			this.hbox5.Add (this.combobox5);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.combobox5]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			this.hbox3.Add (this.hbox5);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.hbox5]));
			w9.Position = 2;
			w9.Expand = false;
			w9.Fill = false;
			this.vbox7.Add (this.hbox3);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hbox3]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			this.hbox2.Add (this.vbox7);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.vbox7]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			this.vbox2.Add (this.hbox2);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox2]));
			w12.Position = 1;
			w12.Expand = false;
			w12.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.vbox9 = new global::Gtk.VBox ();
			this.vbox9.Name = "vbox9";
			this.vbox9.Spacing = 6;
			// Container child vbox9.Gtk.Box+BoxChild
			this.label7 = new global::Gtk.Label ();
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Bad Input! Default values (4, 7) will be used!");
			this.vbox9.Add (this.label7);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.label7]));
			w13.Position = 0;
			w13.Expand = false;
			w13.Fill = false;
			this.vbox2.Add (this.vbox9);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.vbox9]));
			w14.PackType = ((global::Gtk.PackType)(1));
			w14.Position = 2;
			w14.Expand = false;
			w14.Fill = false;
			this.hbox1.Add (this.vbox2);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox2]));
			w15.Position = 1;
			w15.Expand = false;
			w15.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.button3 = new global::Gtk.Button ();
			this.button3.CanFocus = true;
			this.button3.Name = "button3";
			this.button3.UseUnderline = true;
			this.button3.Label = global::Mono.Unix.Catalog.GetString ("Generate");
			this.vbox3.Add (this.button3);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.button3]));
			w16.Position = 0;
			w16.Expand = false;
			w16.Fill = false;
			this.hbox1.Add (this.vbox3);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox3]));
			w17.Position = 2;
			w17.Expand = false;
			w17.Fill = false;
			this.Add (this.hbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 427;
			this.DefaultHeight = 87;
			this.combobox4.HasDefault = true;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.button3.Clicked += new global::System.EventHandler (this.OnButton3Clicked);
		}
	}
}
